"""empty message

Revision ID: 3007cfa67a59
Revises: 
Create Date: 2020-02-08 12:26:33.377879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3007cfa67a59'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keep',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=True),
    sa.Column('slug', sa.String(length=140), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('keep')
    # ### end Alembic commands ###
